example1 Message ::= { 
    header IdentityBlock {
            keyType {
              algorithm rsa,
              parameter {
                keySize 1024
              }
            },
            publicKey '010101111'B
        },
        serial 42,
        maxReplays 0,
        valid {},
        decryptionKey 'ACF12121212121212121'H,
        requests {}  
    },
    blocks 'AFCFFFCDE12392861263126387634817'H
}