\begin{document}

% *****************************************************************************************
% ***  Titel
% *****************************************************************************************
\begin{frame}<presentation>[label=title]{~}{}
\maketitle
\end{frame}
\teachernotes[Mitnehmen]{
\begin{itemize}
\item Poster
\item Handout
\item Notebook mit Adapter
\end{itemize}
}


% *****************************************************************************************
% ***  Inhalt
% *****************************************************************************************
\newpage
\begin{frame}<presentation>[label=toc]{Inhalt}
\begin{block}{Inhalt}
\mode<presentation>{\setcounter{tocdepth}{2}\normalsize\tableofcontents}
\end{block}
\end{frame}
\showslide{toc}

\mode<article>{\setcounter{tocdepth}{4}  
\tableofcontents}



% *****************************************************************************************
% ***  Ziele der Defense
% *****************************************************************************************
\newpage
\mode<all>{\mySection[General]{General}}
\mode<all>{\mySubsection[Goals]{Goals}}
\begin{frame}<presentation>[label=goals]{General}{Goals}
  \begin{block}{Main Goals are ...}
    \begin{itemize}
      \item ... to have a common understanding of the PhD topic.
      \item ... to have an agreement on the focus of the thesis.
      \item ... to have an agreement on the expected outcome of thesis. 
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{goals}

\teachernotes[09:20]{
  \begin{itemize}
    \item Abhohlen ob diese Ziele dem generellen Verständnis entsprechen.
  \end{itemize}
}

% *****************************************************************************************
% ***  Definition system
% *****************************************************************************************
\newpage
\mode<all>{\mySection[Definitions]{Definititons}}
\mode<all>{\mySubsection[System]{System}}
\begin{frame}<presentation>[label=system]{Definitions}{System}
  \begin{block}{Definition of system}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{system}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Definition user
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[User]{User}}
\begin{frame}<presentation>[label=user]{Definitions}{User}
  \begin{block}{Definition of user}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{user}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Definition observer
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[Observer]{Observer}}
\begin{frame}<presentation>[label=observer]{Definitions}{Observer}
  \begin{block}{Definition of observer}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{observer}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Definition owner
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[Owner]{Owner}}
\begin{frame}<presentation>[label=owner]{Definitions}{Owner}
  \begin{block}{Definition of owner}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{owner}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Definition node
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[Node]{Node}}
\begin{frame}<presentation>[label=node]{Definitions}{Node}
  \begin{block}{Definition of Node}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{node}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Required Attributes (Protocol)
% *****************************************************************************************
\newpage
\mode<all>{\mySection[Requirements]{Requirements}}
\mode<all>{\mySubsection[Protocol]{Protocol}}
\begin{frame}<presentation>[label=protocol]{Requirements}{Protocol}
  \begin{block}{Protocol requirements}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{protocol}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Required Attributes (Infrastructure)
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[Infrastructure]{Infrastructure}}
\begin{frame}<presentation>[label=infrastructure]{Requirements}{Infrastructure}
  \begin{block}{Infrastructure requirements}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{infrastructure}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Required Attributes (acceptance)
% *****************************************************************************************
\newpage
\mode<all>{\mySubsection[Acceptance]{Acceptance}}
\begin{frame}<presentation>[label=acceptance]{Requirements}{Acceptance}
  \begin{block}{Acceptance requirements}
    \begin{itemize}
      \item FIXME
    \end{itemize}  
  \end{block}
\end{frame}
\showslide{acceptance}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Thesis content
% *****************************************************************************************
\newpage
\mode<all>{\mySection[Thesis]{Thesis}}
\mode<all>{\mySubsection[Content]{Content}}
\begin{frame}<presentation>[label=thesiscontent]{Thesis}{Content}
  \begin{block}{Proposed thesis content is ...}
    {\tiny
    \begin{itemize}
      \item Create a generic approach to transport messages through public networks unobserved.
      \item Create a generic implementation (traffic generator) of the approach.
      \item Do traffic analysis against the approach to identify weaknesses. \\Focus lies on:
      \begin{itemize}\tiny
        \item Identifying endpoints of communication.
        \item Identifying messages, message types or parts of them.
        \item Identifying patterns of service usage.
        \item Identifying weaknesses in robustnes.
      \end{itemize}
      \item Create a working minimal prototype based on the findings.
    \end{itemize}}
  \end{block}
\end{frame}
\showslide{thesiscontent}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

% *****************************************************************************************
% ***  Discussion
% *****************************************************************************************
\newpage
\mode<all>{\mySection[Discusion]{Discussion}}
\begin{frame}<presentation>[label=discussion]{Discussion}{}
~
\end{frame}
\showslide{discussion}

\teachernotes[FIXME]{
  \begin{itemize}
    \item FIXME
  \end{itemize}
}

\end{document}